# The important parts of the code

## Command imports

In [308]:
%pylab inline 
import os
import nibabel as nib
import numpy as np
import glob
from scipy.ndimage import label
from numpy.linalg import inv

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


## Import mse IDs 

In [309]:
#subjects = np.genfromtxt("pbr_baselines.txt", dtype=str)
subjects = ["mse1474"]
all_sub_results = [["mseID",
                   "lesion number and type",      
                   "number of subcortical lesions",
                   "number of juxtacortical lesions",
                   "number of periventricular lesions",
                   "number of infratentorial lesions",
                   "number of errors"]]
print subjects[:5]

['mse1474']


## Set variables to lesion/segmentation files, freeview cmdline copy and paste

In [310]:
for les_file in glob.glob("/data/henry7/PBR/subjects/%s/lesions_manual/*/alignment_lesions.nii.gz" % subjects[0]):
    print les_file
for seg_file in glob.glob("/data/henry7/PBR/subjects/%s/masks/*/segmentation.nii.gz" % subjects[0]):
    print seg_file
for gm_file in glob.glob("/data/henry6/PBR/surfaces/*%s*/mri/ribbon.mgz" % subjects[0]):
    print gm_file

print
print "Freeview link:"
print 
print "freeview", seg_file, les_file, gm_file

/data/henry7/PBR/subjects/mse1474/lesions_manual/ms242-mse1474-002-AX_T1_3D_IRSPGR/alignment_lesions.nii.gz
/data/henry7/PBR/subjects/mse1474/masks/ms242-mse1474-002-AX_T1_3D_IRSPGR/segmentation.nii.gz
/data/henry6/PBR/surfaces/ms242-mse1474-002-AX_T1_3D_IRSPGR/mri/ribbon.mgz

Freeview link:

freeview /data/henry7/PBR/subjects/mse1474/masks/ms242-mse1474-002-AX_T1_3D_IRSPGR/segmentation.nii.gz /data/henry7/PBR/subjects/mse1474/lesions_manual/ms242-mse1474-002-AX_T1_3D_IRSPGR/alignment_lesions.nii.gz /data/henry6/PBR/surfaces/ms242-mse1474-002-AX_T1_3D_IRSPGR/mri/ribbon.mgz


## Binarize

enlarged_gm = Binarize(in_file=rib_file, match=3, dilate=3, binary_file='/home/mkhan/Temp_Binary/%s' % subjects[0])
enlarged_gm.cmdline

## Obtain affines 

In [311]:
les_img = nib.load(les_file)
les_img.dataobj
seg_img = nib.load(seg_file)
seg_img.dataobj
gm_img = nib.load(gm_file)
gm_img.dataobj

les_data = les_img.get_data()
print les_data.shape
seg_data = seg_img.get_data()
print seg_data.shape
gm_data = gm_img.get_data()
print gm_data.shape

les_affine = les_img.get_affine()
print les_affine
gm_affine = gm_img.get_affine()
print gm_affine
seg_affine = seg_img.get_affine()
print seg_affine
inv_seg_affine = np.linalg.inv(seg_affine)
print inv_seg_affine

(256, 256, 150)
(256, 256, 256)
(256, 256, 256)
[[  -0.9375        0.            0.          122.45800018]
 [   0.            0.9375        0.          -78.72650146]
 [   0.            0.            1.          -49.06119919]
 [   0.            0.            0.            1.        ]]
[[  -1.            0.            0.          130.45800018]
 [   0.            0.            1.          -86.72650146]
 [   0.           -1.            0.          158.93880081]
 [   0.            0.            0.            1.        ]]
[[  -1.            0.            0.          130.45800781]
 [   0.            0.            1.          -86.72650146]
 [   0.           -1.            0.          158.938797  ]
 [   0.            0.            0.            1.        ]]
[[  -1.           -0.           -0.          130.45800781]
 [  -0.           -0.           -1.          158.938797  ]
 [   0.            1.            0.           86.72650146]
 [   0.            0.            0.            1.        ]]


## set labels for coordinates

In [312]:
#lesion labels
les_labels, n_les_labels = label(les_data==[1])

#segmentation - brainstem labels
seg_brainstem_labels, n_seg_brainstem_labels = label(seg_data==[16])
seg_lcerebellumcortex_labels, n_seg_lcerebellumcortex_labels = label(seg_data==[8])
seg_rcerebellumcortex_labels, n_seg_rcerebellumcortex_labels = label(seg_data==[47])
seg_lcerebellumwm_labels, n_seg_lcerebellumwm_labels = label(seg_data==[7])
seg_rcerebellumwm_labels, n_seg_rcerebellumwm_labels = label(seg_data==[46])

#segmentation - lateral ventricle labels
seg_llv_labels, n_seg_llv_labels = label(seg_data==[4])
seg_rlv_labels, n_seg_rlv_labels = label(seg_data==[43])

#gm labels
gm_lh_labels, n_gm_lh_labels = label(gm_data==3)
gm_rh_labels, n_gm_rh_labels = label(gm_data==42)

## debugging tools for labels

In [313]:
print n_les_labels #prints number of lesion labels

print n_seg_brainstem_labels #prints number of labels in brainstem

print n_gm_lh_labels #prints number of labels in gray matter

print n_seg_llv_labels #prints number of labels in ventricle

print np.bincount(les_labels.ravel()) #prints volumes of lesions

print np.bincount(seg_lcerebellumwm_labels.ravel()) #prints volume of left cerebellum white matter

print np.bincount(gm_rh_labels.ravel()) #prints volume of left hemisphere gray matter

print np.bincount(seg_llv_labels.ravel()) #prints volume of left hemisphere ventricle

17
1
37
2
[9818227     326      77    4141      23      94      94      57      39
    5620     793      79     133     174     384      29      37      73]
[16766117    11099]
[16537293   239875        1        1        1        1        1        1
        1        1        2        1        1        1        1        1
        6        2        4        2        1        1        1       12
        1        1        2]
[16771052     5845      319]


## Function that gets coordinates from labels

In [314]:
def get_label_coord(labels,num_labels):
    all_label_coords = []
    if num_labels >= 1:
        for count in range(1, num_labels+1):
            cur_label_coords = []
            x,y,z = np.nonzero(labels==count)
            for count2 in range(len(x)):
                cur_coord = [x[count2],y[count2],z[count2]]
                cur_label_coords.append(cur_coord)
            all_label_coords.append(cur_label_coords)
    else:
        x,y,z = np.nonzero(labels==1)
        for count in range(len(x)):
            all_label_coords.append([x[count],y[count],z[count]])
    #for count in range(nlabels):
    #    print "lesion #", count+1, "", all_les_coords[count]
    #    print ""
    return all_label_coords

## Function that converts coordinates to real space

In [315]:
def get_rs_coord(coordinates,affine):
    all_rs_coords = []
    for count in range(len(coordinates)):
        cur_rs_coords = []
        for count2 in range(len(coordinates[count])):
            rs_coord = np.dot(affine, [coordinates[count][count2][0],
                                           coordinates[count][count2][1], 
                                           coordinates[count][count2][2],
                                           1])
            rs_coord_noone = [rs_coord[0],rs_coord[1],rs_coord[2]] #raw float
            #rs_coord_noone = [round(rs_coord[0],2),round(rs_coord[1],2),round(rs_coord[2],2)] #two decimal float
            #rs_coord_noone = [int(rs_coord[0]),int(rs_coord[1]),int(rs_coord[2])] #integers
            cur_rs_coords.append(rs_coord_noone)
        all_rs_coords.append(cur_rs_coords)
    #for count in range(nlabels):
    #    print "lesion #", count+1, "", all_rs_coords[count]
    #    print ""
    return all_rs_coords

## Function that converts coordinates to segmentation file coordinates

In [316]:
def get_seg_coord(coordinates):
    all_seg_coords = []
    for count in range(len(coordinates)):
        cur_seg_coords = []
        for count2 in range(len(coordinates[count])):
            seg_coord = np.dot(inv_seg_affine, [coordinates[count][count2][0],
                                                coordinates[count][count2][1], 
                                                coordinates[count][count2][2],
                                                1])
            #seg_coord_noone = [seg_coord[0],seg_coord[1],seg_coord[2]] #raw float
            #seg_coord_noone = [round(seg_coord[0],2),round(seg_coord[1],2),round(seg_coord[2],2)] #two decimal float
            seg_coord_noone = [int(seg_coord[0]),int(seg_coord[1]),int(seg_coord[2])] #integers
            cur_seg_coords.append(seg_coord_noone)
        all_seg_coords.append(cur_seg_coords)
    #for count in range(nlabels):
    #    print "lesion #", count+1, "", all_seg_coords[count]
    #    print ""
    return all_seg_coords

## Generate midbrain coordinates into a variable

In [317]:
bs = get_label_coord(seg_brainstem_labels,n_seg_brainstem_labels)
lcc = get_label_coord(seg_lcerebellumcortex_labels,n_seg_lcerebellumcortex_labels)
lcw = get_label_coord(seg_lcerebellumwm_labels,n_seg_lcerebellumwm_labels)
rcc = get_label_coord(seg_rcerebellumcortex_labels,n_seg_rcerebellumcortex_labels)
rcw = get_label_coord(seg_rcerebellumwm_labels,n_seg_rcerebellumwm_labels)

midbrain = []

if len(bs) != 1:
    midbrain.append(bs[1])
else:
    midbrain.append(bs[0])

if len(lcc) != 1:
    midbrain.append(lcc[1])
else:
    midbrain.append(lcc[0])

if len(lcw) != 1:
    midbrain.append(lcw[1])
else:
    midbrain.append(lcw[0])

if len(rcc) != 1:
    midbrain.append(rcc[1])
else:
    midbrain.append(rcc[0])

if len(rcw) != 1:
    midbrain.append(rcw[1])
else:
    midbrain.append(rcw[0])

print len(midbrain)



5


## Generate lesion coordinates into a variable

In [318]:
lesions_les = get_label_coord(les_labels,n_les_labels)
lesions = get_seg_coord(get_rs_coord(lesions_les,les_affine))
lesions_seg = lesions
"""
print len(lesions)
print lesions_seg[0][1]
print lesions_les[7]
print lesions_seg[7]
print lesions_les[7][39]
print lesions_seg[7][39]
"""

'\nprint len(lesions)\nprint lesions_seg[0][1]\nprint lesions_les[7]\nprint lesions_seg[7]\nprint lesions_les[7][39]\nprint lesions_seg[7][39]\n'

## Generate gray matter coordinates into a variable

In [319]:
gm = []
lhcoord = get_label_coord(gm_lh_labels,n_gm_lh_labels)
rhcoord = get_label_coord(gm_rh_labels,n_gm_rh_labels)
lhcoord_seg = get_seg_coord(get_rs_coord(lhcoord,gm_affine))
rhcoord_seg = get_seg_coord(get_rs_coord(rhcoord,gm_affine))

if len(lhcoord_seg) != 1:
    gm.append(lhcoord_seg[1])
else:
    gm.append(lhcoord_seg[0])
if len(rhcoord_seg) != 1:
    gm.append(rhcoord_seg[1])
else:
    gm.append(rhcoord_seg[0])

print len(gm)

2


## Generate ventricular coordinates into a variable

In [320]:
ventricles = []
vlhcoord = get_label_coord(seg_llv_labels,n_seg_llv_labels)
vrhcoord = get_label_coord(seg_rlv_labels,n_seg_rlv_labels)

if len(vlhcoord) != 1:
    ventricles.append(vlhcoord[1])
else:
    ventricles.append(vlhcoord[0])
if len(vrhcoord) != 1:
    ventricles.append(vrhcoord[1])
else:
    ventricles.append(vrhcoord[0])

print len(ventricles)

2


## Convert coordinates from nested lists to strings

In [321]:
def convert_coord_str(coordinates):
    coord_str = []
    for x in range(len(coordinates)):
        str_int = []
        for y in range(len(coordinates[x])):
            str_int.append(str(coordinates[x][y]))
        coord_str.append(str_int)
    return coord_str

lesions_str = convert_coord_str(lesions)
midbrain_str = convert_coord_str(midbrain)

## Infratentorial Check V2 

In [322]:
les_type = []
count = 0
while count <= (len(lesions_str))-1:
    lesion_type = ""
    x = set(lesions_str[count])
    count2 = 0
    while count2 <= (len(midbrain_str))-1:
        y = set(midbrain_str[count2])
        testint = x.isdisjoint(y)
        if testint == False:
            count2 = len(midbrain_str)
        count2 += 1
    if testint == False:
        lesion_type = "infratentorial"
    else:
        lesion_type = "subcortical"
    print count+1, lesion_type
    les_type.append(lesion_type)
    count += 1

1 subcortical
2 subcortical
3 subcortical
4 subcortical
5 infratentorial
6 subcortical
7 subcortical
8 infratentorial
9 subcortical
10 subcortical
11 subcortical
12 subcortical
13 subcortical
14 subcortical
15 infratentorial
16 subcortical
17 subcortical


## append results to a new list 

In [323]:
results = []
sub_count, inf_count, jux_count, per_count, err_count = 0, 0, 0, 0, 0
for count in range(len(les_type)):
    results.append([count+1, les_type[count]])
    if les_type[count] == "subcortical":
        sub_count += 1
    elif les_type[count] == "infratentorial":
        inf_count += 1
    elif les_type[count] == "juxtacortical":
        jux_count += 1
    elif les_type[count] == "periventricular":
        per_count += 1
    else:
        err_count += 1
all_sub_results.append([subjects[0], 
                        results, 
                        sub_count, 
                        jux_count,
                        per_count,
                        inf_count, 
                        err_count]
                      )
print all_sub_results

[['mseID', 'lesion number and type', 'number of subcortical lesions', 'number of juxtacortical lesions', 'number of periventricular lesions', 'number of infratentorial lesions', 'number of errors'], ['mse1474', [[1, 'subcortical'], [2, 'subcortical'], [3, 'subcortical'], [4, 'subcortical'], [5, 'infratentorial'], [6, 'subcortical'], [7, 'subcortical'], [8, 'infratentorial'], [9, 'subcortical'], [10, 'subcortical'], [11, 'subcortical'], [12, 'subcortical'], [13, 'subcortical'], [14, 'subcortical'], [15, 'infratentorial'], [16, 'subcortical'], [17, 'subcortical']], 14, 0, 0, 3, 0]]


In [324]:
print lesions[4][4]
print lesions[7][4]
print lesions[14][8]

[107, 181, 94]
[117, 178, 111]
[159, 187, 91]


# The debugging portions of the code

## Infratentorial Lesion Check

les_type = []
for count in range(len(lesions)):
    lesion_type = ""
    count4 = 0
    if len(lesions[count]) <= 500:
        for count2 in range(len(lesions[count])):
            halt = ""
            for count3 in range(len(midbrain)):
                for count4 in range(len(midbrain[count3])):
                    if lesions[count][count2] == midbrain[count3][count4]:
                        lesion_type = "infratentorial"
                        halt = "stop"
                    if halt == "stop":
                        continue
                if halt == "stop":
                    continue
            if halt == "stop":
                continue
        if lesion_type == "":
            lesion_type = "subcortical"
        print count, "done, type is:", lesion_type
        les_type.append(lesion_type)
    else:
        print "skipped lesion number", count, "; too large"
        les_type.append("too large")

print les_type

## Debugging function that finds range of values in brain lesion/segment

In [325]:
test_x = [];test_y=[];test_z=[]
for count in range(len(midbrain[0])):
    test_x.append(midbrain[0][count][0])
    test_y.append(midbrain[0][count][1])
    test_z.append(midbrain[0][count][2])

def range_coord(val_list):
    min_val = min(val_list)
    max_val = max(val_list)
    print min_val,"-", max_val

range_coord(test_x);range_coord(test_y);range_coord(test_z)

114 - 145
149 - 208
92 - 123


## Debugging Function that searches for coordinates in any given brain lesion/segment

In [326]:
def search(coordinates,check_coord):
    number = 0
    for count in range(len(coordinates)):
        if check_coord == coordinates[count]:
            number = count + 1
            print count
    if number == 0:
        print "not available"
    else:
        print "available"

#search(midbrain[0],lesions[7][39])
#search(midbrain[0],[144, 177, 100])
#search(lesions[7],lesions[7][39])

## Attempt at understanding "any" function

In [327]:
test = any(count for lesions[7][39] in midbrain)
print test

<generator object <genexpr> at 0x7ff08bcb9320>


## Function that takes in coordinates for lesions, and outputs average; may not actually use this

In [328]:
def average_func(coordinates):
    averages_all = []
    for count in range(len(coordinates)):
        averages = []
        sumx=0;sumy=0;sumz=0
        for count2 in range(len(coordinates[count])):
            sumx += coordinates[count][count2][0]
            sumy += coordinates[count][count2][1]
            sumz += coordinates[count][count2][2]
        average_x = sumx / len(coordinates[count])
        average_y = sumy / len(coordinates[count])
        average_z = sumz / len(coordinates[count])
        averages = [average_x, average_y, average_z]
        averages_all.append(averages)
        #print count, averages
    return averages_all

In [329]:
average_les = average_func(get_label_coord(les_labels, n_les_labels))
average_rs = average_func(get_rs_coord(get_label_coord(les_labels, n_les_labels)))
average_seg = average_func(get_seg_coord(get_rs_coord(get_label_coord(les_labels, n_les_labels))))

allcoord_les = get_label_coord(les_labels, n_les_labels)
allcoord_rs = get_rs_coord(get_label_coord(les_labels, n_les_labels))
allcoord_seg = get_seg_coord(get_rs_coord(get_label_coord(les_labels, n_les_labels)))

print average_les[0]
print average_rs[0]
print average_seg[0]
print allcoord_les[0][0]
print allcoord_rs[0][0]
print allcoord_seg[0][0]

print average_seg

print lesions[8][20]

TypeError: get_rs_coord() takes exactly 2 arguments (1 given)

## Debugging Coding Section

In [ ]:
realspace_coordinates = np.dot(les_affine, [average_les[0][0],
                 average_les[0][1], 
                 average_les[0][2],
                 1])
average_les[0] 
realspace_coordinates
from numpy.linalg import inv
inv_seg_affine = np.linalg.inv(seg_affine)
freesurfer_matrix = np.dot(inv_seg_affine, [realspace_coordinates[0],
                                            realspace_coordinates[1], 
                                            realspace_coordinates[2],
                                            1])
print average_les[0]; print realspace_coordinates; print freesurfer_matrix

print len(midbrain[0])

les_type = []

"""for test_count in range(len(lesions)):
    for count in range(len(lesions[test_count])):
        for count2 in range(len(midbrain)):
            halt = ""
            for count3 in range(len(midbrain[count2])):
                if lesions[test_count][count] == midbrain[count2][count3]:
                    inf_num += 1
                    lesion_type = "infratentorial"
                    halt = "stop"
                    break
            if halt == "stop":
                break
    print lesion_type
if lesion_type == "infratentorial":
    les_type.append(lesion_type)
elif lesion_type == "":
    les_type.append("subcortical")
print les_type
print inf_num
"""