## Command imports

In [2]:
%pylab inline 
import os
import nibabel as nib
import numpy as np
import glob
from scipy.ndimage import label
from numpy.linalg import inv

Populating the interactive namespace from numpy and matplotlib


## Import mse IDs 

In [3]:
#subjects = np.genfromtxt("pbr_baselines.txt", dtype=str)
subjects = ["mse1343"]
print subjects[:5]

['mse1343']


## Set variables to lesion/segmentation files

In [4]:
for les_file in glob.glob("/data/henry7/PBR/subjects/%s/lesions_manual/*/alignment_lesions.nii.gz" % subjects[0]):
    print les_file
for seg_file in glob.glob("/data/henry7/PBR/subjects/%s/masks/*/segmentation.nii.gz" % subjects[0]):
    print seg_file
    
print seg_file, les_file

/data/henry7/PBR/subjects/mse1343/lesions_manual/ms69-mse1343-002-AX_T1_3D_IRSPGR/alignment_lesions.nii.gz
/data/henry7/PBR/subjects/mse1343/masks/ms69-mse1343-002-AX_T1_3D_IRSPGR/segmentation.nii.gz
/data/henry7/PBR/subjects/mse1343/masks/ms69-mse1343-002-AX_T1_3D_IRSPGR/segmentation.nii.gz /data/henry7/PBR/subjects/mse1343/lesions_manual/ms69-mse1343-002-AX_T1_3D_IRSPGR/alignment_lesions.nii.gz


## Obtain affines 

In [5]:
les_img = nib.load(les_file)
les_img.dataobj
seg_img = nib.load(seg_file)
seg_img.dataobj

les_data = les_img.get_data()
print les_data.shape
seg_data = seg_img.get_data()
print seg_data.shape

les_affine = les_img.get_affine()
print les_affine
seg_affine = seg_img.get_affine()
print seg_affine
inv_seg_affine = np.linalg.inv(seg_affine)
print inv_seg_affine

(256, 256, 150)
(256, 256, 256)
[[  -0.9375        0.            0.          118.36100006]
 [   0.            0.9375        0.          -74.62950134]
 [   0.            0.            1.          -27.06119919]
 [   0.            0.            0.            1.        ]]
[[  -1.            0.            0.          126.36100769]
 [   0.            0.            1.          -82.62950134]
 [   0.           -1.            0.          182.938797  ]
 [   0.            0.            0.            1.        ]]
[[  -1.           -0.           -0.          126.36100769]
 [  -0.           -0.           -1.          182.938797  ]
 [   0.            1.            0.           82.62950134]
 [   0.            0.            0.            1.        ]]


## set labels for coordinates

In [6]:
#lesion labels
les_labels, n_les_labels = label(les_data==[1])

#segmentation labels
seg_brainstem_labels, n_seg_brainstem_labels = label(seg_data==[16])
seg_lcerebellumcortex_labels, n_seg_lcerebellumcortex_labels = label(seg_data==[8])
seg_rcerebellumcortex_labels, n_seg_rcerebellumcortex_labels = label(seg_data==[47])
seg_lcerebellumwm_labels, n_seg_lcerebellumwm_labels = label(seg_data==[7])
seg_rcerebellumwm_labels, n_seg_rcerebellumwm_labels = label(seg_data==[46])

## debugging tools for labels

In [7]:
print n_les_labels #prints number of lesion labels

print n_seg_brainstem_labels #prints number of labels in brainstem

print np.bincount(les_labels.ravel()) #prints volumes of lesions

print np.bincount(seg_lcerebellumwm_labels.ravel()) #prints volume of left cerebellum white matter

14
2
[9802412      34   10765      30      43     962     608   15063      54
     159      36      89      56      33      56]
[16762636    14580]


## Function that gets coordinates from labels

In [48]:
def get_label_coord(labels,num_labels):
    all_label_coords = []
    if num_labels >= 1:
        for count in range(1, num_labels+1):
            cur_label_coords = []
            x,y,z = np.nonzero(labels==count)
            for count2 in range(len(x)):
                cur_coord = [x[count2],y[count2],z[count2]]
                cur_label_coords.append(cur_coord)
            all_label_coords.append(cur_label_coords)
    else:
        x,y,z = np.nonzero(labels==1)
        for count in range(len(x)):
            all_label_coords.append([x[count],y[count],z[count]])
    #for count in range(nlabels):
    #    print "lesion #", count+1, "", all_les_coords[count]
    #    print ""
    return all_label_coords

## Function that converts coordinates to real space

In [9]:
def get_rs_coord(coordinates):
    all_rs_coords = []
    for count in range(len(coordinates)):
        cur_rs_coords = []
        for count2 in range(len(coordinates[count])):
            rs_coord = np.dot(les_affine, [coordinates[count][count2][0],
                                           coordinates[count][count2][1], 
                                           coordinates[count][count2][2],
                                           1])
            rs_coord_noone = [rs_coord[0],rs_coord[1],rs_coord[2]] #raw float
            #rs_coord_noone = [round(rs_coord[0],2),round(rs_coord[1],2),round(rs_coord[2],2)] #two decimal float
            #rs_coord_noone = [int(rs_coord[0]),int(rs_coord[1]),int(rs_coord[2])] #integers
            cur_rs_coords.append(rs_coord_noone)
        all_rs_coords.append(cur_rs_coords)
    #for count in range(nlabels):
    #    print "lesion #", count+1, "", all_rs_coords[count]
    #    print ""
    return all_rs_coords

## Function that converts coordinates to segmentation file coordinates

In [10]:
def get_seg_coord(coordinates):
    all_seg_coords = []
    for count in range(len(coordinates)):
        cur_seg_coords = []
        for count2 in range(len(coordinates[count])):
            seg_coord = np.dot(inv_seg_affine, [coordinates[count][count2][0],
                                                coordinates[count][count2][1], 
                                                coordinates[count][count2][2],
                                                1])
            #seg_coord_noone = [seg_coord[0],seg_coord[1],seg_coord[2]] #raw float
            #seg_coord_noone = [round(seg_coord[0],2),round(seg_coord[1],2),round(seg_coord[2],2)] #two decimal float
            seg_coord_noone = [int(seg_coord[0]),int(seg_coord[1]),int(seg_coord[2])] #integers
            cur_seg_coords.append(seg_coord_noone)
        all_seg_coords.append(cur_seg_coords)
    #for count in range(nlabels):
    #    print "lesion #", count+1, "", all_seg_coords[count]
    #    print ""
    return all_seg_coords

## Generate midbrain coordinates

In [59]:
midbrain_int = []
bs = get_label_coord(seg_brainstem_labels,n_seg_brainstem_labels)
lcc = get_label_coord(seg_lcerebellumcortex_labels,n_seg_lcerebellumcortex_labels)
lcw = get_label_coord(seg_lcerebellumwm_labels,n_seg_lcerebellumwm_labels)
rcc = get_label_coord(seg_rcerebellumcortex_labels,n_seg_rcerebellumcortex_labels)
rcw = get_label_coord(seg_rcerebellumwm_labels,n_seg_rcerebellumwm_labels)

midbrain = []
midbrainparts = [brainstem, lcercort, lcerwm, rcercort, rcerwm]

if len(bs) != 1:
    midbrain.append(bs[1])
else:
    midbrain.append(bs[0])

if len(lcc) != 1:
    midbrain.append(lcc[1])
else:
    midbrain.append(lcc[0])

if len(lcw) != 1:
    midbrain.append(lcw[1])
else:
    midbrain.append(lcw[0])

if len(rcc) != 1:
    midbrain.append(rcc[1])
else:
    midbrain.append(rcc[0])

if len(rcw) != 1:
    midbrain.append(rcw[1])
else:
    midbrain.append(rcw[0])

print len(midbrain)



5
14580


21730


## Generate lesion coordinates into a variable

In [12]:
lesions = get_seg_coord(get_rs_coord(get_label_coord(les_labels,n_les_labels)))
lesions_les = get_label_coord(les_labels,n_les_labels)
lesions_seg = lesions

print len(lesions)
print lesions_seg[0][1]
print lesions_les[7]
print lesions_seg[7]
print lesions_les[7][39]
print lesions_seg[7][39]


14
[80, 133, 113]
[[139, 94, 33], [140, 94, 33], [140, 95, 33], [141, 95, 33], [141, 95, 34], [142, 95, 33], [142, 96, 33], [142, 96, 34], [142, 97, 33], [142, 97, 34], [143, 95, 33], [143, 96, 32], [143, 96, 33], [143, 96, 34], [143, 97, 32], [143, 97, 33], [143, 97, 34], [143, 98, 33], [143, 98, 34], [144, 95, 33], [144, 95, 34], [144, 96, 32], [144, 96, 33], [144, 96, 34], [144, 97, 32], [144, 97, 33], [144, 97, 34], [144, 98, 32], [144, 98, 33], [144, 99, 32], [144, 99, 33], [145, 95, 33], [145, 95, 34], [145, 96, 32], [145, 96, 33], [145, 96, 34], [145, 97, 32], [145, 97, 33], [145, 98, 32], [145, 98, 33], [145, 99, 32], [145, 99, 33], [145, 100, 32], [146, 95, 33], [146, 96, 32], [146, 96, 33], [146, 97, 32], [146, 97, 33], [146, 98, 32], [146, 98, 33], [146, 99, 32], [147, 95, 33], [147, 96, 32], [147, 96, 33]]
[[138, 176, 96], [139, 176, 96], [139, 176, 97], [140, 176, 97], [140, 175, 97], [141, 176, 97], [141, 176, 98], [141, 175, 98], [141, 176, 98], [141, 175, 98], [142, 176

## Debugging function that finds range of values in brain lesion/segment

In [13]:
test_x = [];test_y=[];test_z=[]
for count in range(len(midbrain[0])):
    test_x.append(midbrain[0][count][0])
    test_y.append(midbrain[0][count][1])
    test_z.append(midbrain[0][count][2])

def range_coord(val_list):
    min_val = min(val_list)
    max_val = max(val_list)
    print min_val,"-", max_val

range_coord(test_x);range_coord(test_y);range_coord(test_z)

109 - 146
148 - 207
83 - 117


## Debugging Function that searches for coordinates

In [26]:
def search(coordinates,check_coord):
    number = 0
    for count in range(len(coordinates)):
        if check_coord == coordinates[count]:
            number = count + 1
            print count
    if number == 0:
        print "not available"
    else:
        print "available"

search(midbrain[0],lesions[7][39])
search(midbrain[0],[144, 177, 100])
search(lesions[7],lesions[7][39])

not available
not available
28
39
available


## Function that takes in coordinates for lesions, and outputs average; may not actually use this

In [15]:
def average_func(coordinates):
    averages_all = []
    for count in range(len(coordinates)):
        averages = []
        sumx=0;sumy=0;sumz=0
        for count2 in range(len(coordinates[count])):
            sumx += coordinates[count][count2][0]
            sumy += coordinates[count][count2][1]
            sumz += coordinates[count][count2][2]
        average_x = sumx / len(coordinates[count])
        average_y = sumy / len(coordinates[count])
        average_z = sumz / len(coordinates[count])
        averages = [average_x, average_y, average_z]
        averages_all.append(averages)
        #print count, averages
    return averages_all

In [16]:
average_les = average_func(get_label_coord(les_labels, n_les_labels))
average_rs = average_func(get_rs_coord(get_label_coord(les_labels, n_les_labels)))
average_seg = average_func(get_seg_coord(get_rs_coord(get_label_coord(les_labels, n_les_labels))))

allcoord_les = get_label_coord(les_labels, n_les_labels)
allcoord_rs = get_rs_coord(get_label_coord(les_labels, n_les_labels))
allcoord_seg = get_seg_coord(get_rs_coord(get_label_coord(les_labels, n_les_labels)))

print average_les[0]
print average_rs[0]
print average_seg[0]
print allcoord_les[0][0]
print allcoord_rs[0][0]
print allcoord_seg[0][0]

print average_seg

[78, 113, 75]
[44.54666182574104, 31.804322186638327, 48.70350669412052]
[81, 133, 113]
[77, 113, 75]
[46.173500061035156, 31.307998657226562, 47.938800811767578]
[80, 134, 113]
[[81, 133, 113], [102, 126, 88], [97, 138, 160], [99, 158, 97], [107, 133, 152], [142, 135, 151], [158, 133, 87], [142, 176, 98], [143, 125, 141], [142, 148, 148], [147, 152, 53], [149, 148, 149], [152, 122, 144], [180, 108, 120]]


## Infratentorial Lesion Check

In [62]:
les_type = []
inf_num = 0
for count in range(len(lesions)):
    lesion_type = ""
    count4 = 0
    for count2 in range(len(lesions[count])):
        for count3 in range(len(midbrain)):
            halt = ""
            for count4 in range(len(midbrain[count3])):
                if lesions[count][count2] == midbrain[count3][count4]:
                    inf_num += 1
                    lesion_type = "infratentorial"
                    halt = "stop"
                    break
            if halt == "stop":
                break
    if lesion_type == "infratentorial":
        les_type.append(lesion_type)
    elif lesion_type == "":
        les_type.append("subcortical")

print les_type
print inf_num

KeyboardInterrupt: 

In [18]:
test = any(count for lesions[7][39] in midbrain)
print test

<generator object <genexpr> at 0x7f64a844cdc0>


### Not part of program, but this worked for one set of coordinates so loop data is compared to this

In [60]:
realspace_coordinates = np.dot(les_affine, [average_les[0][0],
                 average_les[0][1], 
                 average_les[0][2],
                 1])
average_les[0] 
realspace_coordinates
from numpy.linalg import inv
inv_seg_affine = np.linalg.inv(seg_affine)
freesurfer_matrix = np.dot(inv_seg_affine, [realspace_coordinates[0],
                                            realspace_coordinates[1], 
                                            realspace_coordinates[2],
                                            1])
print average_les[0]; print realspace_coordinates; print freesurfer_matrix

print len(midbrain[0])

les_type = []

for count in range(len(lesions[7])):
    for count2 in range(len(midbrain)):
        halt = ""
        for count3 in range(len(midbrain[count2])):
            if lesions[7][count] == midbrain[count2][count3]:
                inf_num += 1
                lesion_type = "infratentorial"
                halt = "stop"
                break
        if halt == "stop":
            break
    print lesion_type
if lesion_type == "infratentorial":
    les_type.append(lesion_type)
elif lesion_type == "":
    les_type.append("subcortical")

print les_type
print inf_num

[78, 113, 75]
[ 45.23600006  31.30799866  47.93880081   1.        ]
[  81.12500763  134.99999619  113.9375        1.        ]
21730
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
infratentorial
['infratentorial']
53
